### ISSUE TITLE
[Feature] Start here! pages

### ISSUE THREAD

**Issue by davidchiii** [osirislab/ctf101#17]
Include a section on where to start.

Include:
- how do i play ctf
- types of ctf
- where to find CTF
- benefits of a VM or native terminal
- download links for python, wsl, wireshark whatever
- toolkit stuff

**Comment by VaughnValle** [comment]
I think download links and relevant resources for tools/software already exists under [docs/faq/recommended-software.md](https://github.com/osirislab/ctf101/blob/master/docs/faq/recommended-software.md)

**Comment by davidchiii** [comment]
Closed in #18
